# Generated by Django 2.1 on 2018-09-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', 'add_counties_subcounties_courts_prisons_offences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissibilityform',
            name='petitioner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petitions.PetitionForm'),
        ),
    ]
