# Generated by Django 2.0.7 on 2018-08-19 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', 'add_counties_and_subcounties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='county',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
