# Generated by Django 2.1 on 2018-09-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_auto_20180914_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionform',
            options={'ordering': ('-created',), 'permissions': (('can_edit_petitionform', 'User can edit a petition'), ('can_delete_petitionform', 'User can delete a petition'), ('can_view_petitionforms', 'User can view all petitions'), ('can_create_petitionform', 'User can create a petition'))},
        ),
    ]
