# Generated by Django 2.0.7 on 2018-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_auto_20180819_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
