# Generated by Django 2.1 on 2018-09-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20180914_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionform',
            options={'ordering': ('-created',), 'permissions': (('can_view_petitionforms', 'User can view all petitions'),)},
        ),
    ]
