# Generated by Django 2.1 on 2018-09-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_auto_20180914_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissibilityform',
            options={'ordering': ('-created',), 'permissions': (('can_view_admissibilityform', 'User can view all admissibilities'), ('can_view_myadmissibilityform', 'User can view all my admissibilities'))},
        ),
        migrations.AlterModelOptions(
            name='exit',
            options={'ordering': ('-created',), 'permissions': (('can_view_exits', 'User can view all exits'), ('can_view_myexits', 'User can view all my exits'))},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ('-created',), 'permissions': (('can_view_grants', 'User can view all grants'), ('can_view_mygrants', 'User can view all my grants'))},
        ),
        migrations.AlterModelOptions(
            name='hearingsummary',
            options={'ordering': ('-created',), 'permissions': (('can_view_hearingsummary', 'User can view all hearings'), ('can_view_mypetitionsummary', 'User can view all my hearings'))},
        ),
        migrations.AlterModelOptions(
            name='interviewsummary',
            options={'ordering': ('-created',), 'permissions': (('can_view_interviews', 'User can view all interviews'), ('can_view_myinterviews', 'User can view all my interviews'))},
        ),
        migrations.AlterModelOptions(
            name='petitionsummary',
            options={'ordering': ('-created',), 'permissions': (('can_view_petitionsummary', 'User can view all summaries'), ('can_view_mypetitionsummary', 'User can view all my summaries'))},
        ),
        migrations.AlterModelOptions(
            name='recommendationform',
            options={'ordering': ('-created',), 'permissions': (('can_view_recommendations', 'User can view all recommendations'), ('can_view_myrecommendations', 'User can view all my recommendations'))},
        ),
    ]
