# Generated by Django 2.1 on 2018-09-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0005_auto_20180914_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionform',
            options={'ordering': ('-created',), 'permissions': (('can_view_petitionforms', 'User can view all petitions'), ('can_view_mypetitionforms', 'User can view all my petitions'), ('can_view_petitionformstatus', 'User can view the status of petitions'))},
        ),
    ]
