# Generated by Django 2.1 on 2018-09-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_auto_20180914_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissibilityform',
            options={'ordering': ('-created',), 'permissions': (('can_view_admissibilityform', 'User can view all admissibilities'), ('can_view_myadmissibilityform', 'User can view all my admissibilities'), ('can_print_admissibilityform', 'User can view print admissibility form'), ('can_view_admissibilityformdetails', 'User can view details of admissibility'))},
        ),
    ]
