# Generated by Django 2.0.7 on 2018-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '01000_add_counties_subcounties_courts_prisons_offences'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationform',
            name='circumstanceofoffence',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='recommendationform',
            name='compellingremarks',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
