# Generated by Django 2.0.7 on 2018-11-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '1001_auto_20181031_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationform',
            options={'ordering': ('-created',), 'permissions': (('can_view_recommendations', 'User can view all recommendations'), ('can_view_myrecommendations', 'User can view all his/her recommendations'), ('can_print_recommendations', 'User can  print a recommendation'), ('can_view_recommendationdetails', 'User can view details of a recommendation'), ('can_view_master_recommendations', 'User can view master_recommendations'))},
        ),
    ]
