# Generated by Django 2.0.7 on 2019-01-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '1002_auto_20181101_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionform',
            options={'ordering': ('-created',), 'permissions': (('can_view_petitionforms', 'User can view all petitions'), ('can_view_mypetitionforms', 'User can view all my petitions'), ('can_view_petitionformstatus', 'User can view the status of petitions'), ('can_view_duplicatesfinder', 'User can view the petitions duplicates'), ('can_view_petitionformdetails', 'User can view the details of petitions'), ('can_view_main_dashboard', 'User can view main dashboard'), ('can_view_more_reports', 'User can view more reports dashboard'))},
        ),
    ]
