# Generated by Django 2.0.7 on 2019-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '1003_auto_20190110_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='exitdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
