# Generated by Django 2.0.7 on 2019-02-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '1004_exit_exitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionsummary',
            name='admissibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petitions.PetitionForm'),
        ),
    ]
