# Generated by Django 2.0.7 on 2019-05-14 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '1006_auto_20190514_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionform',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
